server:
  port: 9006
spring:
  application:
    name: hrm-page
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hrm_pages
      username: root
      password: 123456
mybatis-plus:
  mapper-locations: classpath:com/tzq/hrm/mapper/*Mapper.xml
  type-aliases-package: com.tzq.hrm.domain,com.tzq.hrm.query
